Triviolivia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.models import User
from rest_framework import routers, serializers, viewsets



urlpatterns = [
    path('admin/', admin.site.urls),
    path('configure/', include('configure.urls')),
    path('compete/', include('compete.urls')),
    path('', include('main.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('api/', include('api.urls')),
]

api/urls.py
from django.urls import path 
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

urlpatterns = [
    path('questions/', views.QuestionList.as_view()),
    path('questions/<int:pk>/', views.QuestionDetail.as_view()),
    path('users/', views.UserList.as_view()),
    path('categories/', views.CategoryList.as_view()),
    path('eras/', views.EraList.as_view()),
    path('difficulties/', views.DifficultyList.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

configure/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework import routers

from . import views
from .views import *

app_name = 'configure'
urlpatterns = [
    path('', views.main, name='main'),
    
    path('question/', views.question_list, name='question-list'),
    path('question/create/', QuestionCreateView.as_view(), name='question-create'),
    path('question/batch/', views.batch, name='question-batch'),
    path('question/<int:pk>/update/', QuestionUpdateView.as_view(), name='question-update'),
    path('question/<int:pk>/delete/', QuestionDeleteView.as_view(), name='question-delete'),
    path('question/deleteall/', views.delete_all, name='delete-all'),
    path('question/search/', views.search_questions, name='search-questions'),
    path('question/export', views.export_to_csv, name='export-to-csv'),
    path('question/listify', views.listify_eras, name='listify-eras'),
    
    path('category/', CategoryListView.as_view(), name='category-list'),
    path('category/create/', CategoryCreateView.as_view(), name='category-create'),
    path('category/<int:pk>/update/', CategoryUpdateView.as_view(), name='category-update'),
    path('category/<int:pk>/delete/', CategoryDeleteView.as_view(), name='category-delete'),

    path('subcategory/', SubcategoryListView.as_view(), name='subcategory-list'),
    path('subcategory/create/', SubcategoryCreateView.as_view(), name='subcategory-create'),
    path('subcategory/<int:pk>/update/', SubcategoryUpdateView.as_view(), name='subcategory-update'),
    path('subcategory/<int:pk>/delete/', SubcategoryDeleteView.as_view(), name='subcategory-delete'),

    path('era/', EraListView.as_view(), name='era-list'),
    path('era/create/', EraCreateView.as_view(), name='era-create'),
    path('era/<int:pk>/update/', EraUpdateView.as_view(), name='era-update'),
    path('era/<int:pk>/delete/', EraDeleteView.as_view(), name='era-delete'),

    path('difficulty/', DifficultyListView.as_view(), name='difficulty-list'),
    path('difficulty/create/', DifficultyCreateView.as_view(), name='difficulty-create'),
    path('difficulty/<int:pk>/update/', DifficultyUpdateView.as_view(), name='difficulty-update'),
    path('difficulty/<int:pk>/delete/', DifficultyDeleteView.as_view(), name='difficulty-delete'),

    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('ajax/load-subcategories/', views.load_subcategories, name='ajax_load_subcategories'),
]

main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main, name='main'),
    path('login/', views.login_request, name='login'),
    path("register", views.register_request, name="register"),
    path("logout", views.logout_request, name= "logout"),
]

configure/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=256, blank=True, null=True)

    def __str__(self):
        return f"{self.name}"
    
    class Meta:
        verbose_name_plural = "Categories"

class Subcategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=256, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="subcategories")

    def __str__(self):
        return f"{self.name}"
    
    class Meta:
        verbose_name_plural = "Subcategories"

class Difficulty(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=256, blank=True, null=True)
    score = models.IntegerField()

    def __str__(self):
        return f"{self.name}"
    
    class Meta:
        verbose_name_plural = "Difficulties"

class Era(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=256, blank=True, null=True)

    def __str__(self):
        return f"{self.name}"
    
    class Meta:
        verbose_name_plural = "Eras"

class Tags(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=256, blank=True, null=True)

    def __str__(self):
        return f"{self.name}"
    
    class Meta:
        verbose_name_plural = "Tags"

class Question(models.Model):
    name = models.CharField(max_length=64, unique=True,blank=True, null=True)
    text = models.CharField(max_length=511, unique=True)
    response = models.CharField(max_length=256,blank=True, null=True)
    answer = models.CharField(max_length=256)
    score = models.IntegerField(blank=True, null=True)
    difficulty = models.ForeignKey(Difficulty, on_delete=models.CASCADE, related_name="questions")
    eras = models.ManyToManyField(Era, related_name="questions_for_era")
    eras_list= models.CharField(blank=True, null=True, max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="questions")
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE, related_name="questions",blank=True, null=True)
    tags = models.ManyToManyField(Tags, related_name="questions")
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.name}"
    
    def get_eras(self):
        return ", ".join([e.name for e in self.eras.all()])
    
    class Meta:
        verbose_name_plural = "Questions"

configure/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.http import HttpResponse

from .models import *
from .forms import *

import pandas as pd
import csv

# Create your views here.

@login_required
def listify_eras(request):
    questions = Question.objects.all()
    era_not_assigned = Era.objects.get(name="Not Assigned")
    for question in questions:
        
        question.eras_list = ", ".join([e.name for e in question.eras.all()])
    
        if not question.eras_list:
            print('Triggered')
            question.eras.add(era_not_assigned)
            question.save()
            question.eras_list = ", ".join([e.name for e in question.eras.all()])
        
        print(question.text)
        question.save()
    return(redirect('configure:question-list'))
@login_required
def export_to_csv(request):

    question_list = Question.objects.all()
    for q in question_list:
        print(q.eras_list)
    response = HttpResponse('text/csv')
    response['Content-Disposition'] = 'attachment; filename=questions_export.csv'
    writer = csv.writer(response)
    writer.writerow(                       ['text','response','answer','score','difficulty','category','subcategory', 'eras'])
    question_fields = question_list.values_list('text','response','answer','score','difficulty__name','category__name','subcategory__name','eras_list')
    
    for q in question_fields:
        writer.writerow(q)
    return(response)

@login_required
def main(request):

    context = {
        'categories': Category.objects.all()[:25],
        'eras': Era.objects.all()[:25],
        'difficulties': Difficulty.objects.all()[:25],
        'questions': Question.objects.all()[:25],
    }
    return render(request, 'configure/main.html',context)

def  question_list(request):

    if request.method=="POST":
        start_num=int(request.POST.get('start_num'))
        df=pd.read_csv('trivia_questions2.csv',sep=',')

        for q in range(start_num,len(df)):
            print(str(q)+ '. ' + df.iloc[q][4])
            question, created = Question.objects.update_or_create(text=df.iloc[q][4],
                                                    defaults={'answer':df.iloc[q][5],
                                                                'subcategory':Subcategory.objects.get(name=df.iloc[q][0]),
                                                                'category':Category.objects.get(name=df.iloc[q][1]),
                                                                'difficulty':Difficulty.objects.get(score=int(df.iloc[q][2])),
                                                                'author':request.user,
                                                                })


        return redirect('configure:question-list')
           
    context = {
        'questions': Question.objects.all()[:20],
    }

    return render(request, 'configure/question_list.html',context)
    

class QuestionCreateView(LoginRequiredMixin, CreateView):
    model = Question
    template_name = 'configure/question_create.html'
    fields = ['text', 'answer','category', 'subcategory', 'eras', 'difficulty', ]


    def get_success_url(self):
        return reverse('configure:question-list')
    
    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)
    
def batch(request,start_num=0):

    context={}

    return render(request, 'configure/question_batch.html',context)

def delete_all(request):

    Question.objects.all().delete()

    return reverse('configure:main')

def search_questions(request):
    question_results=[]
    if request.method == "POST":
        searched = request.POST['searched']
        question_results = Question.objects.filter(text__contains=searched)

    context={
        'results':question_results
    }

    return render(request, 'configure/search_questions.html', context)

class QuestionUpdateView(UpdateView):
    model = Question
    template_name = 'configure/question_update.html'
    form_class = QuestionUpdateForm
    success_url = reverse_lazy('configure:question-list')

class QuestionDeleteView(DeleteView):
    model = Question
    template_name = 'configure/question_delete.html'
    success_url =  reverse_lazy('configure:question-list')

class CategoryListView(ListView):
    model = Category
    template_name = 'configure/category_list.html'
    context_object_name = 'categories'
    paginate_by = 25

class CategoryDetailView(DetailView):
    model = Category
    template_name = 'configure/category_detail.html'
    context_object_name = 'category'

class CategoryCreateView(CreateView):
    model = Category
    template_name = 'configure/category_create.html'
    fields = ['name', 'description']

    def get_success_url(self):
        return reverse('configure:category-list')

class CategoryUpdateView(UpdateView):
    model = Category
    template_name = 'configure/category_update.html'
    fields = ['name', 'description','title']
    success_url =  reverse_lazy('configure:category-list')

class CategoryDeleteView(DeleteView):
    model = Category
    template_name = 'configure/category_delete.html'
    success_url =  reverse_lazy('configure:category-list')


class SubcategoryListView(ListView):
    model = Subcategory
    template_name = 'configure/subcategory_list.html'
    context_object_name = 'subcategories'
    paginate_by = 25

    def post(self, request, *args, **kwargs):
        df=pd.read_csv('subcategories.csv',sep=',')
        for i in range(len(df)):
            print(df.iloc[i][0])
            subcategory, created = Subcategory.objects.update_or_create(name=df.iloc[i][1],
                                                    defaults={'category':Category.objects.get(name=df.iloc[i][0]),
                                                                })
        return redirect('configure:subcategory-list')

class SubcategoryDetailView(DetailView):
    model = Subcategory
    template_name = 'configure/subcategory_detail.html'
    context_object_name = 'subcategory'

class SubcategoryCreateView(CreateView):
    model = Subcategory
    template_name = 'configure/subcategory_create.html'
    fields = ['name', 'description']

    def get_success_url(self):
        return reverse('configure:subcategory-list')

class SubcategoryUpdateView(UpdateView):
    model = Subcategory
    template_name = 'configure/subcategory_update.html'
    fields = ['name', 'description','title']
    success_url =  reverse_lazy('configure:subcategory-list')

class SubcategoryDeleteView(DeleteView):
    model = Subcategory
    template_name = 'configure/subcategory_delete.html'
    success_url =  reverse_lazy('configure:subcategory-list')

class EraListView(ListView):
    model = Era
    template_name = 'configure/era_list.html'
    context_object_name = 'eras'
    paginate_by = 25

class EraCreateView(CreateView):
    model = Era
    template_name = 'configure/era_create.html'
    fields = ['name', 'description']

    def get_success_url(self):
        return reverse('configure:era-list')

class EraUpdateView(UpdateView):
    model = Era
    template_name = 'configure/era_update.html'
    fields = ['name', 'description']
    success_url =  reverse_lazy('configure:era-list')

class EraDeleteView(DeleteView):
    model = Era
    template_name = 'configure/era_delete.html'
    success_url =  reverse_lazy('configure:era-list')

class DifficultyListView(ListView):
    model = Difficulty
    template_name = 'configure/difficulty_list.html'
    context_object_name = 'difficulties'
    paginate_by = 25

class DifficultyCreateView(CreateView):
    model = Difficulty
    template_name = 'configure/difficulty_create.html'
    fields = ['name', 'description','score']

    def get_success_url(self):
        return reverse('configure:difficulty-list')

class DifficultyUpdateView(UpdateView):
    model = Difficulty
    template_name = 'configure/difficulty_update.html'
    fields = ['name', 'description']
    success_url =  reverse_lazy('configure:difficulty-list')

class DifficultyDeleteView(DeleteView):
    model = Difficulty
    template_name = 'configure/difficulty_delete.html'
    success_url =  reverse_lazy('configure:difficulty-list')

def load_subcategories(request):
    category_id = request.GET.get('category')
    subcategories = Subcategory.objects.filter(category_id=category_id).order_by('name')
    return render(request, 'configure/subcategory_dropdown_list_options.html', {'subcategories': subcategories})

main/views.py
from django.shortcuts import  render, redirect, get_object_or_404
from django.urls import reverse
from django.http import Http404, HttpResponseRedirect

from django.contrib.auth import login, authenticate, logout
from django.contrib import messages

from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.forms.formsets import formset_factory

from django.db import transaction

from django.views.generic.edit import CreateView

import pandas as pd

from configure.models import *
from .forms import *

# Create your views here.


@login_required
def entry(request):


        
    return render(request, 'entry.html',)


def main(request):

	questions = Question.objects.all()
	categories = Category.objects.all().order_by("name")
	eras = Era.objects.filter()
	difficulties = Difficulty.objects.all()

	context = {
		'questions': questions,
		'categories': categories,
		'eras': eras,
		'difficulties': difficulties,
    }

	return render(request,'index.html', context)


def choice_options(request):

	context={
	}

	return render(request, "questionform.html", context)

def register_request(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("main")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm()
	return render (request=request, template_name="register.html", context={"register_form":form})

def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect("main")
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="login.html", context={"login_form":form})\

def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out.") 
	return redirect("main")

configure/templates/configure/category_delete.html
{% extends 'base.html' %} 

{% block content %} 

<h1>Categories</h1>

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}" and all associated questions?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>

{% endblock %}

configure/templates/configure/category_list.html
{% extends 'base.html' %} 

{% block content %} 

<h1>Categories</h1>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Delete</th>
        </tr>
    </thead>

{% for category in object_list %}
    <tbody>
        <tr>
            <td><a href="{% url 'configure:category-update' category.id %}">{{ category.name }}</a></td>
            <td>{{ category.description }}</td>
            <td>
                <a href="{% url 'configure:category-delete' category.id %}">
                    <button class="btn btn-danger">Delete</button>
                </a>
            </td>
        </tr>
    </tbody>
{% empty %}
    No Categories yet.
{% endfor %}
</table>

<a href="{% url 'configure:category-create' %}">
    <button class="btn btn-primary">Create New Category</button>
</a>


{% endblock %}

configure/templates/configure/difficulty_create.html
{% extends 'base.html' %} 

{% block content %} 

<h2>Create a new Difficulty</h2>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>


{% endblock %}

configure/templates/configure/difficulty_delete.html
{% extends 'base.html' %} 

{% block content %} 

<h1>Difficulties</h1>

<form method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    {{ form }}
    <input type="submit" value="Confirm">
</form>

{% endblock %}

configure/templates/configure/difficulty_list.html
{% extends 'base.html' %} 

{% block content %} 

<h1>Difficulties</h1>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Score</th>
            <th>Delete</th>
        </tr>
    </thead>

{% for difficulty in object_list %}
    <tbody>
        <tr>
            <td><a href="{% url 'configure:difficulty-update' difficulty.id %}">{{ difficulty.name }}</a></td>
            <td>{{ difficulty.description }}</td>
            <td>{{ difficulty.score }}</td>
            <td>
                <a href="{% url 'configure:difficulty-delete' difficulty.id %}">
                    <button class="btn btn-danger">Delete</button>
                </a>
            </td>
        </tr>
    </tbody>
{% empty %}
    No Difficulties yet.
{% endfor %}
</table>

<a href="{% url 'configure:difficulty-create' %}">
    <button class="btn btn-primary">Create New Difficulty</button>
</a>


{% endblock %}

configure/templates/configure/difficulty_update.html
{% extends 'base.html' %} 

{% block content %} 

<h1>Difficulties</h1>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

{% endblock %}

configure/templates/configure/era_create.html
{% extends 'base.html' %} 

{% block content %} 

<h2>Create a new Era</h2>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>


{% endblock %}

configure/templates/configure/era_list.html
{% extends 'base.html' %} 

{% block content %} 

<h1>Eras</h1>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Description</th>
            <th>Delete</th>
        </tr>
    </thead>

{% for era in object_list %}
    <tbody>
        <tr>
            <td><a href="{% url 'configure:era-update' era.id %}">{{ era.name }}</a></td>
            <td>{{ era.description }}</td>
            <td>
                <a href="{% url 'configure:era-delete' era.id %}">
                    <button class="btn btn-danger">Delete</button>
                </a>
            </td>
        </tr>
    </tbody>
{% empty %}
    No Eras yet.
{% endfor %}
</table>

<a href="{% url 'configure:era-create' %}">
    <button class="btn btn-primary">Create New Era</button>
</a>


{% endblock %}

configure/templates/configure/era_update.html
{% extends 'base.html' %} 

{% block content %} 

<h1>Eras</h1>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

{% endblock %}

configure/templates/configure/question_batch.html
{% extends 'base.html' %} 

{% block content %} 

<a href="{% url 'configure:question-list'%}"><h1>Questions</h1></a>

{% endblock %}

configure/templates/configure/question_create.html
{% extends 'base.html' %} 

{% block content %} 

<h2>Create a new Question</h2>

<form method="post" id="QuestionCreateForm" data-subcategories-url="{% url 'configure:ajax_load_subcategories' %}" novalidate>
    
    {% csrf_token %}

    <table>
        {{ form.as_table }}
    </table>
    
    <input type="submit" value="Save">
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
  $("#id_category").change(function () {
    var url = $("#questionForm").attr("data-subcategories-url");  // get the url of the `load_cities` view
    var categoryId = $(this).val();  // get the selected country ID from the HTML input
    console.log(categoryId)
    $.ajax({                       // initialize an AJAX request
      url: "https://triviolivia.herokuapp.com/configure/ajax/load-subcategories/",
      data: {
        'category': categoryId       // add the country id to the GET parameters
      },
      success: function (data) {   // `data` is the return of the `load_cities` view function
        $("#id_subcategory").html(data);  // replace the contents of the city input with the data that came from the server
      }
    });

  });
</script>

{% endblock %}

configure/templates/configure/question_list.html
{% extends 'base.html' %} 

{% block content %} 

<h1>Questions</h1>

<h2>Search: </h2>
<form action="{% url 'configure:search-questions' %}" method="POST" class="d-flex">
    {% csrf_token %}
    <input type="text" class="form-control" type="search" aria-label="Search" name="searched">
    <button class="btn-outline-primary" type="submit">Search</button>
</form>
<br>
<a href="{% url 'configure:question-create' %}">
    <button class="btn btn-primary">Create New Question</button>
</a>
<a href="{% url 'configure:listify-eras' %}">
    <button class="btn btn-primary">Listify Eras for Export</button>
</a>

<form action="" method="POST">
    {% csrf_token %}
        <button class="btn btn-secondary" type="submit">Batch Add from CSV</button>
    <input type="number" class="number" name="start_num" id="start_num" width="100px;" placeholder="0">
</form>


<table class="table">
    <thead>
        <tr>
            <th>Text</th>
            <th>Category</th>
            <th>Subcategory</th>
            <th>Eras</th>
            <th>Difficulty</th>
            <th>Active</th>
            <th>Delete</th>
        </tr>
    </thead>

{% for question in questions %}
    <tbody>
        <tr>
            <td><a href="{% url 'configure:question-update' question.id %}">{{ question.text }}</a></td>
            <td>{{ question.category }}</td>
            <td>{{ question.subcategory }}</td>
            <td>{% for era in question.eras.all %}{{era}}, {% endfor %}</td>
            <td>{{ question.difficulty }}</td>
            <td>{{ question.active }}</td>
            <td>
                <a href="{% url 'configure:question-delete' question.id %}">
                    <button class="btn btn-danger">Delete</button>
                </a>
            </td>
        </tr>
    </tbody>
{% empty %}
    No Questions yet.
{% endfor %}
</table>

{% endblock %}

configure/templates/configure/question_update.html
{% extends 'base.html' %} 

{% load crispy_forms_tags %}

{% block content %} 

<h1>Questions</h1>

<form method="post">{% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Update">
</form>

{% endblock %}

configure/templates/configure/subcategory_list.html
{% extends 'base.html' %} 

{% block content %} 

<h1>Subcategories</h1>

<a href="{% url 'configure:subcategory-create' %}">
    <button class="btn btn-primary">Create New Subategory</button>
</a>
<form action="" method="post">
    {% csrf_token %}
    <button action="submit" class="btn btn-outline-secondary">Batch Add</button>
</form>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Category</th>
            <th>Description</th>
            <th>Delete</th>
        </tr>
    </thead>

{% for subcategory in object_list %}
    <tbody>
        <tr>
            <td><a href="{% url 'configure:subcategory-update' subcategory.id %}">{{ subcategory.name }}</a></td>
            <td>{{ subcategory.category.name }}</td>
            <td>{{ subcategory.description }}</td>
            <td>
                <a href="{% url 'configure:subcategory-delete' subcategory.id %}">
                    <button class="btn btn-danger">Delete</button>
                </a>
            </td>
        </tr>
    </tbody>
{% empty %}
    No Subategories yet.
{% endfor %}
</table>

<a href="{% url 'configure:subcategory-create' %}">
    <button class="btn btn-primary">Create New Subategory</button>
</a>


{% endblock %}